apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-deployment
  labels:
    app: jenkins
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      volumes: 
        - name: local-volume
          persistentVolumeClaim:
            claimName: local-pvc
        
      containers:
      - name: jenkins
        image: jenkins/jenkins:latest
        volumeMounts: 
        - mountPath: /var/jenkins_home
          name: local-volume
        ports:
        - containerPort: 8080
